# Generated by Django 4.1.7 on 2023-04-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Empno", models.IntegerField()),
                ("Ename", models.CharField(max_length=100)),
                ("Job", models.CharField(max_length=100)),
                ("Mgr", models.IntegerField()),
                ("Hiredate", models.DateField()),
                ("Sal", models.IntegerField()),
                ("Comm", models.IntegerField()),
                ("Deptno", models.IntegerField()),
                ("Ehttp", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Dept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Dname", models.CharField(max_length=100)),
                ("Dloc", models.CharField(max_length=100)),
                (
                    "Empno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.emp"
                    ),
                ),
            ],
        ),
    ]
