from django.shortcuts import render
from django.http import HttpResponse
# from django.db.models.functions import Length
from django.db.models. functions import Length
# Create your views here.
from app.models import *

def Emp_datails(request):
    A1=int(input('Empno:'))
    B2=input('Ename:')
    C3=input('Job:')
    D4=input('Mgr:')
    E5=input('Hiredate:')
    F6=input('Sal:')
    G7=input('Comm:')
    I8=input('Deptno:')
    J9=input('Ehttp:')
    EO=Emp.objects.get_or_create(Empno=A1,Ename=B2,Job=C3,Mgr=D4,Hiredate=E5,Sal=F6,Comm=G7,Deptno=I8,Ehttp=J9)[0]
    EO.save()
    return HttpResponse("date Inserrd ")

def Dept_details(request):
    A1=input('Empno:')
    B2=input('Ename:')
    C3=input('Job:')
    D4=input('Mgr:')
    E5=input('Hiredate:')
    F6=input('Sal:')
    G7=input('Comm:')
    I8=input('Deptno:')
    J9=input('Ehttp')
    D10=input("Dname:")
    D11=input("Dol:") 
    EO=Emp.objects.get_or_create(Empno=A1,Ename=B2,Job=C3,Mgr=D4,Hiredate=E5,Sal=F6,Comm=G7,Deptno=I8,Ehttp=J9)[0]
    EO.save()
    EO2=Dept.objects.get_or_create(Empno=EO,Dname=D10,Dloc=D11)[0]
    EO2.save()
    return HttpResponse("Date inserted into in Dept table")


def one(request):
    Q=Emp.objects.all()
    # Q=Emp.objects.filter(Ename='Miller')
    # Q=Emp.objects.order_by('-Ename')
    # Q=Emp.objects.order_by(Length('Ename'))
    # Q=Emp.objects.order_by(Length('Ename').desc())
    # Q=Emp.objects.exclude(Ename="Miller")
    # Q=Emp.objects.filter(Sal__lte=1000)
    # Q=Emp.objects.filter(Hiredate__month='2')
    # Q=Emp.objects.filter(Hiredate__year__gt='2000')
    # Q=Emp.objects.filter(Ename__startswith='m')
    Q=Emp.objects.filter(Ename__contains='r')
    # Q=Emp.objects.filter(Ename__regex=r'['a-z']') 
    # Emp.objects.filter(Ename='Miller').update(Ename='XYZ')
    # Emp.objects.all().update(Ename='miller')
    # Emp.objects.filter(Mgr=100).update(Ename='XYZ')
    Emp.objects.filter(Sal=800).update(Ename="Rocky")    
    Emp.objects.update_or_create(Ename='something',defaults={'Empno':'2345','Job':'sd','Mgr':'432','Hiredate':'1999-12-12','Sal':'67','Comm':'7654','Deptno':'10','Ehttp':'dsdf'})
    # Q=Emp.objects.filter(Ename='Vishnu')
    # Q=Emp.objects.order_by('Empno')
    # Q=Emp.objects.order_by(-'Empno')
    # Q=Emp.objects.order_by(Length('Ename').desc())
    # Q=Emp.objects.exclude(Ename='Vishnu')
    # Q=Emp.objects.filter(Hiredate__month='2')
    # Q=Emp.objects.filter(Hiredate__year__lt='10')
    # Q=Emp.objects.all()
    # Q=Emp.objects.filter(Ename__contains='S')
    # Q=Emp.objects.all()
    # Q=Emp.objects.filter(Sal__lt='10000')
    # Q=Emp.objects.filter(Hiredate__day='10')
    # Q=Emp.objects.filter(Ename__endswith='s')
    # Q=Emp.objects.filter(Ename__in=('miller','smith'))
    # Q=Emp.objects.filter(Ename__regex=r'[\w]')
    # LOA=AccessRecord.objects.filter(date__gt='2022-10-10')
    Q=Emp.objects.all()
    Q=Emp.objects.filter(Ename='Allen')
    Q=Emp.objects.order_by("Ename")
    Q=Emp.objects.order_by("-Ename")
    Q=Emp.objects.order_by(Length('Sal'))
    Q=Emp.objects.exclude(Ename="Allen")
    Q=Emp.objects.filter(Sal__lt='1000')
    Q=Emp.objects.filter(Sal__gt='1000')
    Q=Emp.objects.filter(Sal__gte='1221')
    Q=Emp.objects.filter(Sal__lte='80')
    Q=Emp.objects.filter(Hiredate__year='2000')
    Q=Emp.objects.filter(Hiredate__month='0')
    Q=Emp.objects.filter(Hiredate__day='02')
    Q=Emp.objects.filter(Ename__startswith='a')
    Q=Emp.objects.filter(Ename__startswith='m')
    Q=Emp.objects.filter(Ename__in=('Allen','Miller'))
    Q=Emp.objects.filter(Ename__in=('Allen','Miller'))
    Q=Emp.objects.filter(Ename__contains='s')
    Q=Emp.objects.filter(Sal__regex=r'0-9')
    # Q=Emp.objects.f ilter(Ename='Allen').update(S)
    Emp.objects.filter(Mgr=105).update(Ename='XYZ')
    Emp.objects.filter(Mgr=102).update(Ename='ASDFGHJ')
    Emp.objects.all().update(Ename='Yadav')
    Emp.objects.all().update(Sal='100121')

    Emp.objects.update_or_create(Ename='something',defaults={'Empno':'2345','Job':'sd','Mgr':'432','Hiredate':'1999-12-12','Sal':'67','Comm':'7654','Deptno':'10','Ehttp':'dsdf'})
    Emp.objects.update_or_create(Ename='somet',defaults={'Empno':'1211','Job':'eq','Mgr':'342','Hiredate':'2002-01-12','Sal':'3212','Comm':'322','Deptno':'20','Ehttp':'dsa'})
    # Emp.objects.filter(Mgr=)
    Emp.objects.update_or_create(Ename='something',defaults={'Empno':'2345','Job':'srewd','Mgr':'12432','Hiredate':'1999-12-12','Sal':'67','Comm':'7654','Deptno':'10','Ehttp':'dsdf'})
    Emp.objects.filter(Ename='something').delete()
    Q=Emp.objects.all()
    d={'A':Q}
    # Q=Emp.objects.get(Empno='2345')
    # Emp.objects.filter(Ename='XYZ').delete()
    # Emp.objects.all().delete()
    # Emp.objects.order_by('Ename')
    return render(request,"one.html",d)
#     LOA=AccessRecord.objects.filter(date__gt='2022-10-10')
#     LOA=AccessRecord.objects.filter(date__gte='2022-10-10')
#     LOA=AccessRecord.objects.filter(date__lt='2022-10-10')
#     LOA=AccessRecord.objects.filter(date__lte='2022-10-10')
#     LOA=AccessRecord.objects.filter(date__year='2023')
#     LOA=AccessRecord.objects.filter(date__month='10')
#     LOA=AccessRecord.objects.filter(date__day='5')
#     LOA=AccessRecord.objects.filter(date__year__gt='2023')
#     LOA=AccessRecord.objects.filter(date__month__lt='10')
#     LOW=Webpage.objects.filter(n'ame__startswith='k')
#     LOW=Webpage.objects.filter(email__endswith='.com')
#     LOW=Webpage.objects.filter(name__contains='S')
#     LOW=Webpage.objects.filter(name__in=('ashu','yAsh'))
#     LOW=Webpage.objects.filter(name__regex='[a-zA-Z]{7}')
#     LOW=Webpage.objects.filter(Q(topic_name='Cricket') & Q(name='dhoni'))
#     LOW=Webpage.objects.filter(Q(topic_name='Cricket'))

#     def display_access(request):
#     LOA=AccessRecord.objects.all()
#     LOA=AccessRecord.objects.filter(date__gt='2022-10-10')
#     LOA=AccessRecord.objects.filter(date__gte='2022-10-10')
#     LOA=AccessRecord.objects.filter(date__lt='2022-10-10')
#     LOA=AccessRecord.objects.filter(date__lte='2022-10-10')

#     d={'access':LOA}
#     return render(request,'display_access.html',d)

def two(request):
    P=Dept.objects.all()
    d={'B':P}
    return render(request,"two.html",d)